name: Sync site

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Sync
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install --user -r requirements.txt
      - name: Update metadata
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./sync.py
      - name: Commit and push
        run: |
          # Do not enable branch protection for main; it'll break this.
          git config user.name 'CoreOS Bot'
          git config user.email coreosbot@fedoraproject.org
          git add docs/data/*
          git commit -m "Update data 📦"
          git push
